services:
  postgres:
    image: postgres:9.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
